head:
- - meta
  - content: '#F37121'
    name: theme-color
- - meta
  - content: true
    name: apple-mobile-web-app-capable
- - meta
  - content: black
    name: apple-mobile-web-app-status-bar-style
- - link
  - rel: shortcut icon
    href: https://www.jointheleague.org/wp-content/uploads/2022/06/favicon-32x32-1.png
    type: image/x-icon
- - link
  - rel: icon
    type: image/png
    sizes: 16x16
    href: /icons/favicon-16x16.png
- - link
  - rel: icon
    type: image/png
    sizes: 96x96
    href: /icons/favicon-96x96.png
- - link
  - rel: icon
    type: image/png
    sizes: 96x96
    href: /icons/favicon-96x96.png
plugins:
- '@vuepress/plugin-back-to-top'
- '@vuepress/plugin-medium-zoom'
themeConfig:
  displayAllHeaders: true
  docsDir: ''
  editLinkText: ''
  editLinks: false
  lastUpdated: false
  logo: /assets/Flag.png
  nav:
  - link: /about/
    text: About
  - link: https://jointheleague.org
    text: The LEAGUE
  repo: ''


